const teachers = [
  {
    id: 1,
    fullname: "Dr. Anirban Chatterjee",
    hqualification: "M.Sc Mathematics",
    experience: 8,
    employment: "govt",
    expertise: "Mathematics, Physics",
    email: "anirban@bee.com",
    phonenumber: "9876543210",
    gender: "male",
    city: "Kolkata",
    pincode: "700001",
    bio: "Specializing in calculus and competitive exam logic."
  },
  {
    id: 2,
    fullname: "Ms. Priyanka Das",
    hqualification: "M.A English",
    experience: 4,
    employment: "private",
    expertise: "English Literature, Spoken English",
    email: "priyanka@bee.com",
    phonenumber: "9123456780",
    gender: "female",
    city: "Bhadreswar",
    pincode: "712124",
    bio: "Focusing on interactive communication and grammar."
  },
  {
    id: 3,
    fullname: "Mr. Arup Sen",
    hqualification: "B.Tech Computer Science",
    experience: 6,
    employment: "corporate",
    expertise: "React, JavaScript, Python",
    email: "arup@bee.com",
    phonenumber: "9988776655",
    gender: "male",
    city: "Howrah",
    pincode: "711101",
    bio: "Hands-on coding projects for young developers."
  },
  {
    id: 4,
    fullname: "Mrs. Sohini Roy",
    hqualification: "M.Sc Chemistry",
    experience: 10,
    employment: "freelance",
    expertise: "Organic Chemistry, NEET Prep",
    email: "sohini@bee.com",
    phonenumber: "9090909090",
    gender: "female",
    city: "Durgapur",
    pincode: "713201",
    bio: "Helping students decode complex chemical reactions."
  },
  {
    id: 5,
    fullname: "Amitava Ghosh",
    hqualification: "M.A Sanskrit",
    experience: 12,
    employment: "govt",
    expertise: "Sanskrit, Bengali",
    email: "amitava@bee.com",
    phonenumber: "9830012345",
    gender: "male",
    city: "Chinsurah",
    pincode: "712101",
    bio: "Preserving heritage through language and literature."
  },
  {
    id: 6,
    fullname: "Srijita Mukherjee",
    hqualification: "B.Sc Biology",
    experience: 3,
    employment: "private",
    expertise: "Botany, Zoology",
    email: "srijita@bee.com",
    phonenumber: "9433112233",
    gender: "female",
    city: "Chandannagar",
    pincode: "712136",
    bio: "Passionate about making biology visual and fun."
  },
  {
    id: 7,
    fullname: "Vikram Malhotra",
    hqualification: "MBA Finance",
    experience: 15,
    employment: "corporate",
    expertise: "Economics, Commerce",
    email: "vikram@bee.com",
    phonenumber: "9874455667",
    gender: "male",
    city: "Kolkata",
    pincode: "700016",
    bio: "Practical insights into the world of business and finance."
  },
  {
    id: 8,
    fullname: "Kavita Iyer",
    hqualification: "M.Sc Physics",
    experience: 7,
    employment: "freelance",
    expertise: "Astrophysics, Quantum Mechanics",
    email: "kavita@bee.com",
    phonenumber: "9007123456",
    gender: "female",
    city: "Bidhannagar",
    pincode: "700091",
    bio: "Exploring the mysteries of the universe with students."
  },
  {
    id: 9,
    fullname: "Rahul Banerjee",
    hqualification: "B.A Geography",
    experience: 5,
    employment: "private",
    expertise: "Social Studies, Geography",
    email: "rahulb@bee.com",
    phonenumber: "8899001122",
    gender: "male",
    city: "Serampore",
    pincode: "712201",
    bio: "Mapping the world through engaging storytelling."
  },
  {
    id: 10,
    fullname: "Deepa Karmakar",
    hqualification: "M.P.Ed (Physical Education)",
    experience: 9,
    employment: "govt",
    expertise: "Sports Science, Yoga",
    email: "deepa@bee.com",
    phonenumber: "7766554433",
    gender: "female",
    city: "Asansol",
    pincode: "713301",
    bio: "Promoting fitness and mental health in the hive."
  }
];

export default teachers;